In [2]:
from numpy import *

In [3]:
arr = array([1,7,8,9])
print(arr)

[1 7 8 9]


In [4]:
arr2 = arr + 5
print(arr2)

[ 6 12 13 14]


In [5]:
id(arr)

1555657068432

In [6]:
id(arr2)

1555657068816

In [13]:
matrix = array([[1,5,6,3],[86,25,36,41]])
print(matrix)

[[ 1  5  6  3]
 [86 25 36 41]]


In [10]:
one_array = matrix.flatten()

In [11]:
print(one_array)

[ 1  5  6  3 86 25 36 41]


In [18]:
reshaping_array = matrix.reshape(2,2,2) # creating 2 dimensional arrays, 2 d arrays and 2 columns in it
print(reshaping_array)

[[[ 1  5]
  [ 6  3]]

 [[86 25]
  [36 41]]]


In [23]:
diag = diagonal.matrix
print(diag)

AttributeError: 'numpy._ArrayFunctionDispatcher' object has no attribute 'matrix'

In [24]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the diagonal
diag = np.diagonal(matrix)
print(diag)


[1 5 9]


In [27]:
import numpy as np

matrix2 = np.array([[1, 5, 7],
                   [4, 5, 5],
                   [2, 8, 4]])

# Get the diagonal
diag2 = np.diagonal(matrix2)
print(diag2)


[1 5 4]


In [28]:
print(matrix * matrix2)

[[ 1 10 21]
 [16 25 30]
 [14 64 36]]


In [29]:
print(matrix @ matrix2)  # use @ in python to matrix multiply


[[ 15  39  29]
 [ 36  93  77]
 [ 57 147 125]]


In [30]:
def greats():
    print("hello")
    print("good morning")
    

In [31]:
greats()

hello
good morning


In [1]:
# types of  arguments
def add(a,b): # a, b are formal arguments
    c = a + b 
    print(c)
add(5,2) # 5,2 are actual arguments
    

7


In [4]:
def persons_name(name,age): # here postion arguments is passed
    print(name,age)
    
persons_name('venky','25')

venky 25


In [8]:
def persons_name(name,age): # here keyword  arguments is passed
    print(name,age)
    
persons_name (age = '25', name ='venky')

venky 25


In [2]:
def persons_name(name,age = 16): # here default arguments is passed
    print(name,age)

persons_name('venky ') # here default age is 16 because of default arguments is passed
persons_name('venky',25)   

venky 16
venky 25


In [3]:
def addingnum(a,*b):
    c = a + b
    print(c)

addingnum(2,6,8,2)


TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

In [5]:
def addingnum(a,*b): # here b arguments has variable length (means it has n number of values for b gg0
    c = a
    for i in b:
        c = c +i
    print(c)

addingnum(2,6,8,2)


18


In [10]:
def persondata(**data):  # here data is taken from user by using by keyword variable arguments  in a defining function
    print(data)
    for i,j in data.items(): # here  items() is a predefined function used in python to pair the key values
        print(i,j)
persondata(name = 'venky',age ='25') # here keyword variable arguments is passing when function called

{'name': 'venky', 'age': '25'}
name venky
age 25


In [12]:
a = 10  # here a =10 is assigned for global outside function
def something():
    a = 15 # here a is local variable  inside the function
    print("in function",a)
something()

print('outside',a)

in function 15
outside 10


In [13]:
a = 10  # here a =10 is assigned for global outside function
def something():
    global a # here  global a   variable  is used inside the function
    print("in function",a)
something()

print('outside',a)

in function 10
outside 10


In [16]:
a = 10  # here a =10 is assigned for global outside function
def something():
    a = 9
    x = globals()['a']
    print(id(x))

    print('inside ',a)
    globals()[a] = 15 # here global variable is changing inside the function 
something()
print(id(a))

140731591903960
inside  9
140731591903960


In [21]:
# passing the list in function
def count(nums):
    even = 0 
    odd = 0
    for  i in nums:
        if i%2== 0:
            even +=1 # increment for counting
        else:
            odd+=1
    return even,odd
nums = [12,4,10,23,13,57,69] # here list is defined 
even,odd = count(nums)
print(even)
print(odd)

3
4


In [24]:
# fibanocci series
def fib(n):
    a=0
    b=1
    if n == 1:
       print(a)
    else:
        print(a)
        print(b)
    for i in range(2,n):
        c = a+b
        print(c)
        a =b
        b =c
fib(8)

0
1
1
2
3
5
8
13


In [1]:
# factorial 
def fac(a):
    return a*a
result = fac(5)
print(result)
    

25


In [4]:
# anonymous function lambda
result = lambda a : a*a
print(result(5))

25


In [6]:
# filter (functionname,listable)
nums = [2,8,6,9,14,60] 
evens =list(filter(lambda a: a%2 ==0,nums))
print(evens)

[2, 8, 6, 14, 60]


In [8]:
#  map (func,literable)
plus_two = list(map(lambda a: a+a,evens))
print(plus_two)

[4, 16, 12, 28, 120]


In [10]:
 # reduce
from  functools import reduce
sum = reduce(lambda a,b: a+b,plus_two)
print(sum)

180


In [ ]:
# need practice for special variable

In [7]:
# object oeirnted programming
# class 
class computer:
     brand = "lenovo"
# object 
c1 = computer() # here object is defined

print(c1.brand) # here object ia accsesing the attribute


lenovo


In [10]:
class computer:
    def __init__(self,brand):
      self.brand = brand
c1 = computer('lenovo')
c2 = computer('dell')

print(c1.brand)
print(c2.brand)



lenovo
dell


In [13]:
# Define a class (blueprint for creating objects)
class Computer:  
    # Constructor method (runs automatically when an object is created)
    def __init__(self, brand):
        # self refers to the current object
        # brand parameter receives the value passed during object creation
        # self.brand creates an attribute called brand for the object
        self.brand = brand
# Creating first object of the Computer class
# "Lenovo" is passed to the constructor
c1 = Computer("Lenovo")
# Creating second object
# "Dell" is passed to the constructor
c2 = Computer("Dell")
# Accessing the brand attribute using the object
print(c1.brand)   # prints the brand of object c1
# Accessing the brand attribute of the second object
print(c2.brand)   # prints the brand of object c2


Lenovo
Dell


In [21]:
# compare 
class computer:
    def __init__(self,brand):
        self.brand = brand

    def compare(self,other):
        if self.brand == other.brand:
         return True
        else: 
         return False

c1 = computer('lenovo')
c2 = computer('dell')
c3 = computer('lenovo')

print(c1.compare(c2))
print(c1.compare(c3))

False
True


In [30]:
# variables
class  car:
  wheels = 4 # here this class variable used for all variable inside th class is calles static variable
  def __init__(self,miliage,company): # here variables are used  inside __init__ is called as instance variables
    self.miliage = miliage
    self.company = company
c1 = car(10,'bmw')

print(c1.miliage)
print(c1.wheels) # here class variable is used

10
4


In [41]:
# methods 
class student:
    school = 'gitam'

    def __init__(self,m1,m2,m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
    def avg(self): # this is instance method where self is used for object inside the class
        return (self.m1 + self.m2 + self.m3)/3
    def get_m1(self):   # this is instance method i.e accessor method
        return self.m1
    def set_m2(self,value): # this is instance methid i.e mutataor method 
        self.m2 = value
s1 = student(25,45,86)
s2 = student(69,32,47)

print(s1.avg())
print(s1.m2)

52.0
45


In [18]:
# inner class
class  student:
    def __init__(self,name,roll_no):
        self.name = name
        self.roll_no = roll_no
        self.l1 = self.laptop(brand),model_name,ram
    def show(self):
        return self.name,self.roll_no
    class laptop:
        def __init__(self,brand,model_name,ram):
            self.brand = brand
            self.model_name = model_name
            self.ram = ram
        def show(self):
            return self.brand,self.model_name,self.ram
s1 = student('venky','19')
s2 = student('srinu','21')

l1 = s1.laptop('dell','i_7','16gb')


print(s1.l1.show())




NameError: name 'brand' is not defined

In [7]:
# inheritance 
class a:
    def feature1(self):
        print('fearure1 is working')
class b(a): # here class a is inheritaning by class b
    def feature2(self):
        print('fearure2 is working')
a1 = a()
a1.feature1()
b1 = b()
b1.feature1()

class c:
    def feature3(self):
        print('feature3 is working')
class d(a,c): # mutlple inheritance is using by class d 
     def feature4(self):
        print('feature4 is working')
d1 = d()
d1.feature1()  


fearure1 is working


In [5]:
# constructor inheritance
class a:
    def __init__(self):
        print("init 1 is working")
    
    def feature1(self):
        print('fearure1 is working')
class b: # here constructor inheritance checks first for init in class b if not prsent then it goes for class a
    def __init__(self):
        print("init 2 is working")
    def feature2(self):
        print('fearure2 is working')
b1 = b()

        

init 2 is working


In [9]:
# method resolution order 
class a:
    def __init__(self):
        print("init 1 is working")
    def feature(self):
        print('fearure1 is working')
class b:
    def __init__(self):
        print("init 2 is working")
    def feature(self):
        print('fearure2 is working')
class c(a,b):
    def __init__(self):
        super().__init__()# here super keyword is used to call constructor inheritance that follows the left to right i.e a is first then b is second
        print("init 3is working")
    def feature3(self):
        super().feature() # here super keyword is wused to call the method that follows the same method resolution order
  
c1 = c()
c1.feature3()




init 1 is working
init 3is working
fearure1 is working


In [15]:
# polymorphism
# duck typing
class jupyter:
    def excute(self):
        print("spell check")
        print('run')
class pycharm:
    def excute(Self):
        print('run')
class laptop:
    def code(self,ide):
        ide.excute()
ide = jupyter() # here object is using from class jupyter where ide id duck object
lap1 = laptop()
lap1.code(ide)        

spell check
run


In [5]:
a = '5'
b = '6'
print(str.__add__(a,b

                  

56


In [25]:
class student:
    def __init__(self,m1,m2):
        self.m1 = m1
        self.m2 = m2
    def __add__(self,other): #here over loading method is used because # Overloads the + operator for student objects
        m1 = self.m1 + other.m1
        m2 = self.m2 + other.m2
        # Create a new student object with summed marks
        s3 = student(m1,m2)
        return s3

    def __gt__(self,other):   # Overloads > operator to compare two student objects
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        if r1 > r2 :
            return True
        else:
            return False

            
    def __str__(self):# Overloads print() so object displays nicely
        # Returns marks as a formatted string instead of object address
        return '{} {}' .format(self.m1,self.m2)     
    
            
s1 = student(58,69)
s2 = student(60,65)
# Add the two objects (calls __add__ method)
s3 = s1 + s2
print(s3.m1)

# Compare two students (calls __gt__)
if s1 > s2:
    print('s1 wins')
else:
    print('s2 wins')

print(s1)
print(s2)

118
s1 wins
58 69
60 65


In [30]:
# method overloading
class student:
    def __init__(self,m1,m2):
        self.m1 =m1
        self.m2= m2
    def sum(self,a=None,b=None,c=None):
        s=0
        if a!=None and b!=None and c!=None:
            s = a+b+c
        elif a!=None and b!=None:
            s = a+b
        else:
            s =a
        return s
        
s1 = student(58,69)
# Call sum method with 2 arguments
print(s1.sum(5,9))





14


In [15]:
# method over_riding
class a:
    def show(self):
        print('in a show')
class b(a):
    def show(self):
        print('in b show')

a1 = b() # here b show will be seen because class has its show in first class don't have any show after time been its method is over riding
a1.show()

in b show


In [ ]:
# abstract class and abstract method


In [14]:
# iteration
# this are inbulit iteration
nums = [5,6,8,3]
it = iter(nums)
print(it.__next__()) # used iter for printing the nums list
print(next(it)) # similar to above line code we can use both of anyone for priting the list

# user defined iterations

class topten:
    def __init__(self):
        self.num = 1
    def __iter__(self):
        return self
    def __next__(self):
        if self.num <=10:
            val = self.num
            self.num += 1
            return val
        else:
            raise StopIteration

values = topten()

for i in values:
    print(i)




5
6
1
2
3
4
5
6
7
8
9
10


In [30]:
# genarator
# in bulit genators
def topten():

    yield 1
    yield 2
    yield 3
    yield 4
    yield 5
values = topten ()
print(values.__next__())  # print(next(values)) we can use this line also instaed of this

for i in values:
    print(i)

# used defined genarators
def topten():
    n = 1
    while n<= 10:
         sq = n*n # defination of square numbers
         yield sq #yield will  only pause the function and gives  back a value
         n += 1 # iteration used
           
    

   
values = topten ()
print(values.__next__())  # print(next(values)) we can use this line also instaed of this

for i in values:
    print(i)



1
2
3
4
5
1
4
9
16
25
36
49
64
81
100


In [45]:
# error handlin
'''a = 5
b = 2

print (a/b)

a = 5
b = 2
try:
    print(a/b)
    print("resource open")
except ZeroDivisionError:
    print("you can't divide by zero")'''

a = 5
b = 2

try:
    k = int(input("enter the number"))
    print(k)
    print(a/k)
    print("resource open")
    
except ZeroDivisionError as e:
    print("you can't divide by zero" , e)
except ValueError as e:
    print(' you cant do divide by letter' , e)
except Exception as e:
    print('i dont know why')
else:
    print("No error occurred, calculation successful")
finally :
    print('resour close')
    

enter the number 2


2
2.5
resource open
No error occurred, calculation successful
resour close


In [51]:
# threads
from threading import *



In [60]:
import threading
from time import sleep

In [72]:
class hello(Thread):
    def run(self):
         for i in range(5):
             sleep(1)
             print('hello')
   
        
class hi(Thread):
    def run(self):
         for i in range(5):
             sleep(1)
             print('hi')

t1 = hello()
t2 = hi()

t1.start()
sleep(0.5)
t2.start()
t1.join()
t2.join()
print('bye')


hello
hi
hello
hi
hello
hi
hello
hi
hello
hi
bye
hello
hello
hello
hello
hello


In [25]:
from time import sleep

In [32]:
#"r" → Read (default mode)
#"w" → Write (overwrites file)
#"a" → Append (adds data)



f = open('plain_text.txt','r')
print(f.readline(1),end=" ")
sleep(1)
print(f.readline())
print(f.readline())

h i new 

this 1 st line



In [48]:
# code for write
'''f1 = open('sample_write.txt','w')
f1.write("something")
print(f1.read())'''
# code for append
''''f1 = open('sample_write.txt','a')
f1.write("laptop") '''

# code for write all things from one file to other file using a loop
'''f = open('plain_text.txt','r')
f1 = open('sample_write.txt','w')
for data in f:
    f1.write(data)'''

# code to read the data after copying
f1 = open('sample_write.txt','r')
print(f1.read())





hi new 
this 1 st line
this i2 nd line
this is 3 rd line


In [54]:
# code for image file reading
''''f1 = open('WIN_20221004_19_11_53_Pro.jpg','rb') # rb means read binary used for binaray format
print(f1.read())'''
 # code for a copy image file to new file
f1 = open('WIN_20221004_19_11_53_Pro.jpg','rb')  # rb means read binary used for binaray format
f2 = open('mypic.jgp','wb')
for data in f1:
    f2.write(data)



In [73]:
# linear search

a= [1,6,8,4,3,10]
n = int(input("enter the number")) # entering the input from user
def search(a,n):  # we defined the fuction for search
     for i in range(len(a)):
         if a[i] == n:
             return i
            
     return -1
result = search(a, n)

if result != -1:
    print(f"{n} found at index {result}")
else:
    print(f"{n} not found")
         
        
    
        
    

enter the number 5


5 not found


In [78]:
# binary search

a= [1,6,8,4,3,10]
n = int(input("enter the number")) # entering the input from user
low = 0
upper =len(a)-1
def binary_search(a,n):# we defined the fuction for search
    global low,upper   # here gloabl keyword is used
    while low <= upper:
        mid = (low + upper) // 2

        if a[mid] == n:
            return mid
        elif a[mid] < n:
            low =mid+1
        elif a[mid]> n:
            upper =mid-1
    return -1
result = binary_search(a,n)
if result != -1:  # id -1 is not found means the index should wiil come from 0 not -1 
    print(f"{n} found at index {result}")    '''   f"text {variable} text"  '''' # formatted string is used  
else:
    print(f"{n} not found")
            
        
        
    


enter the number 5


5 not found


In [81]:
# bubble sort
a= [1,6,8,4,3,10]

def bubble_sort(a):
    for i in range(len(a)-1,0,-1):
        for j in range(i):
            if a[j] > a[j+1]:
                a[j],a[j+1] =a[j+1],a[j] # we changing the index i.e swaping 
bubble_sort(a)
print(a)


            

[1, 3, 4, 6, 8, 10]


In [88]:
#  selection sort
a= [1,6,8,4,3,10]

def selection_sort(a):
    for i in range(len(a)-1):
       min_index = i
       for j in range(i + 1, len(a)):
            if a[j] < a[min_index]:
                min_index = j
       a[i], a[min_index] = a[min_index], a[i]

selection_sort(a)
print(a)


[1, 3, 4, 6, 8, 10]


In [5]:
# connecting of sql database
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=owl;"
    "Trusted_Connection=yes;"
)


InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'katta\\kvenk\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "owl" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'katta\\kvenk\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "owl" requested by the login. The login failed. (4060)')

In [6]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=master;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()

In [8]:
cursor.execute("CREATE DATABASE mydb")
conn.commit()
print("Database created successfully!")

ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]CREATE DATABASE statement not allowed within multi-statement transaction. (226) (SQLExecDirectW)')

In [9]:
import pyodbc

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=master;"
    "Trusted_Connection=yes;",
    autocommit=True
)

cursor = conn.cursor()

In [10]:
cursor.execute("CREATE DATABASE mydb")
print("Database created successfully!")

Database created successfully!


In [11]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=mydb;"
    "Trusted_Connection=yes;"
)

cursor = conn.cursor()
print("Connected to mydb")

Connected to mydb
